Repository Financial-Times/o-message, pull requests merged in 2020-08, with the labels that each got.

#93 Correct JSDoc type description
  src/js/message.js
Labels: component, release:patch

#94 Add general usage to readme
  README.md
Labels: component, release:patch

#95 Fix build of whitelabel demo Sass
  demos/src/demo.scss
Labels: release:patch

#96 Use the new $default-branch macro instead of hardcoding the branch name
  .github/workflows/percy.yml
Labels: component

#97 Move to Github's native Dependabot
  .dependabot/config.yml
  .github/dependabot.yml
  .github/workflows/automerge.yml
Labels: component

#100 remove the ci section from origami.json
  origami.json
Labels: component
